unisinos:
  smart-health-data:
    mqtt:
      server-url: tcp://localhost:1883
      client-id: alertnode1
      user: pedro
      password: mypassword@123

spring:
  application:
    name: smart-health-data-alert
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/smart-health-data
    username: postgres
    password: mypassword@123
