unisinos:
  smart-health-data:
    mqtt:
      server-url: tcp://localhost:1883
      client-id: node1
      user: pedro
      password: viegas@123
    fog-server:
      mqtt:
        server-url: tcp://localhost:1883
        client-id: node2
        user: pedro
        password: viegas@123

spring:
  application:
    name: smart-health-data-alert
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/smart-health-data-alert
    username: postgres
    password: totvs@123
